# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-08 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_article_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(default='default.png', upload_to='articles/'),
        ),
    ]
